# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: bulutattendance
services:
  app:
    image: bulutattendance
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;database=BulutAttendance;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://mssql:1433;database=BulutAttendance;encrypt=false
      - JHIPSTER_CACHE_REDIS_SERVER=redis://redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mssql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  mssql:
    extends:
      file: ./mssql.yml
      service: mssql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  redis:
    extends:
      file: ./redis.yml
      service: redis
