package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccountingProcedureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingProcedureAllPropertiesEquals(AccountingProcedure expected, AccountingProcedure actual) {
        assertAccountingProcedureAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountingProcedureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingProcedureAllUpdatablePropertiesEquals(AccountingProcedure expected, AccountingProcedure actual) {
        assertAccountingProcedureUpdatableFieldsEquals(expected, actual);
        assertAccountingProcedureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingProcedureAutoGeneratedPropertiesEquals(AccountingProcedure expected, AccountingProcedure actual) {
        assertThat(expected)
            .as("Verify AccountingProcedure auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingProcedureUpdatableFieldsEquals(AccountingProcedure expected, AccountingProcedure actual) {
        assertThat(expected)
            .as("Verify AccountingProcedure relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingProcedureUpdatableRelationshipsEquals(AccountingProcedure expected, AccountingProcedure actual) {
        assertThat(expected)
            .as("Verify AccountingProcedure relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getExecuteAfter()).as("check executeAfter").isEqualTo(actual.getExecuteAfter()));
    }
}
