package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccProcStepAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccProcStepAllPropertiesEquals(AccProcStep expected, AccProcStep actual) {
        assertAccProcStepAutoGeneratedPropertiesEquals(expected, actual);
        assertAccProcStepAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccProcStepAllUpdatablePropertiesEquals(AccProcStep expected, AccProcStep actual) {
        assertAccProcStepUpdatableFieldsEquals(expected, actual);
        assertAccProcStepUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccProcStepAutoGeneratedPropertiesEquals(AccProcStep expected, AccProcStep actual) {
        assertThat(expected)
            .as("Verify AccProcStep auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccProcStepUpdatableFieldsEquals(AccProcStep expected, AccProcStep actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccProcStepUpdatableRelationshipsEquals(AccProcStep expected, AccProcStep actual) {
        assertThat(expected)
            .as("Verify AccProcStep relationships")
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getCreditAccount()).as("check creditAccount").isEqualTo(actual.getCreditAccount()))
            .satisfies(e -> assertThat(e.getDebitAccount()).as("check debitAccount").isEqualTo(actual.getDebitAccount()))
            .satisfies(e -> assertThat(e.getParameter()).as("check parameter").isEqualTo(actual.getParameter()))
            .satisfies(e -> assertThat(e.getProcedure()).as("check procedure").isEqualTo(actual.getProcedure()));
    }
}
