package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllPropertiesEquals(Bank expected, Bank actual) {
        assertBankAutoGeneratedPropertiesEquals(expected, actual);
        assertBankAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllUpdatablePropertiesEquals(Bank expected, Bank actual) {
        assertBankUpdatableFieldsEquals(expected, actual);
        assertBankUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAutoGeneratedPropertiesEquals(Bank expected, Bank actual) {
        assertThat(expected)
            .as("Verify Bank auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableFieldsEquals(Bank expected, Bank actual) {
        assertThat(expected)
            .as("Verify Bank relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableRelationshipsEquals(Bank expected, Bank actual) {
        assertThat(expected)
            .as("Verify Bank relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()));
    }
}
