package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HrLetterTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHrLetterTypeAllPropertiesEquals(HrLetterType expected, HrLetterType actual) {
        assertHrLetterTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertHrLetterTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHrLetterTypeAllUpdatablePropertiesEquals(HrLetterType expected, HrLetterType actual) {
        assertHrLetterTypeUpdatableFieldsEquals(expected, actual);
        assertHrLetterTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHrLetterTypeAutoGeneratedPropertiesEquals(HrLetterType expected, HrLetterType actual) {
        assertThat(expected)
            .as("Verify HrLetterType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHrLetterTypeUpdatableFieldsEquals(HrLetterType expected, HrLetterType actual) {
        assertThat(expected)
            .as("Verify HrLetterType relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHrLetterTypeUpdatableRelationshipsEquals(HrLetterType expected, HrLetterType actual) {
        assertThat(expected)
            .as("Verify HrLetterType relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()));
    }
}
