package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrgPositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgPositionAllPropertiesEquals(OrgPosition expected, OrgPosition actual) {
        assertOrgPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertOrgPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgPositionAllUpdatablePropertiesEquals(OrgPosition expected, OrgPosition actual) {
        assertOrgPositionUpdatableFieldsEquals(expected, actual);
        assertOrgPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgPositionAutoGeneratedPropertiesEquals(OrgPosition expected, OrgPosition actual) {
        assertThat(expected)
            .as("Verify OrgPosition auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgPositionUpdatableFieldsEquals(OrgPosition expected, OrgPosition actual) {
        assertThat(expected)
            .as("Verify OrgPosition relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgPositionUpdatableRelationshipsEquals(OrgPosition expected, OrgPosition actual) {
        assertThat(expected)
            .as("Verify OrgPosition relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()));
    }
}
