package com.bulut.attendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrgUnitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgUnitAllPropertiesEquals(OrgUnit expected, OrgUnit actual) {
        assertOrgUnitAutoGeneratedPropertiesEquals(expected, actual);
        assertOrgUnitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgUnitAllUpdatablePropertiesEquals(OrgUnit expected, OrgUnit actual) {
        assertOrgUnitUpdatableFieldsEquals(expected, actual);
        assertOrgUnitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgUnitAutoGeneratedPropertiesEquals(OrgUnit expected, OrgUnit actual) {
        assertThat(expected)
            .as("Verify OrgUnit auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgUnitUpdatableFieldsEquals(OrgUnit expected, OrgUnit actual) {
        assertThat(expected)
            .as("Verify OrgUnit relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrgUnitUpdatableRelationshipsEquals(OrgUnit expected, OrgUnit actual) {
        assertThat(expected)
            .as("Verify OrgUnit relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getParent()).as("check parent").isEqualTo(actual.getParent()));
    }
}
