package com.bulut.attendance.domain;

import static com.bulut.attendance.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionAccountAllPropertiesEquals(TransactionAccount expected, TransactionAccount actual) {
        assertTransactionAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionAccountAllUpdatablePropertiesEquals(TransactionAccount expected, TransactionAccount actual) {
        assertTransactionAccountUpdatableFieldsEquals(expected, actual);
        assertTransactionAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionAccountAutoGeneratedPropertiesEquals(TransactionAccount expected, TransactionAccount actual) {
        assertThat(expected)
            .as("Verify TransactionAccount auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionAccountUpdatableFieldsEquals(TransactionAccount expected, TransactionAccount actual) {
        assertThat(expected)
            .as("Verify TransactionAccount relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getDebitAmount())
                        .as("check debitAmount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getDebitAmount())
            )
            .satisfies(
                e ->
                    assertThat(e.getCreditAmount())
                        .as("check creditAmount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getCreditAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionAccountUpdatableRelationshipsEquals(TransactionAccount expected, TransactionAccount actual) {
        assertThat(expected)
            .as("Verify TransactionAccount relationships")
            .satisfies(e -> assertThat(e.getInternalUser()).as("check internalUser").isEqualTo(actual.getInternalUser()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getAccount()).as("check account").isEqualTo(actual.getAccount()))
            .satisfies(e -> assertThat(e.getTransaction()).as("check transaction").isEqualTo(actual.getTransaction()));
    }
}
